//
//  DataCamera.swift
//  CameraSpec
//
//  Created by metalbee on 6/21/20.
//  Copyright © 2020 sanengineer. All rights reserved.
//

import UIKit

var cameraMany: [Camera] = [
    Camera(photo: UIImage(named: "canon-eos-r-body-only")!, name: "Canon Eos R", description: "Canon EOS-R sudah resmi masuk di pasar Indonesia melalui datascript. Harga Canon EOS-R untuk body only sekitar 33 Juta Rupiah. Sedangkan untuk Harga EOS-R dengan lensa 24-105 sekitar 49 Juta Rupiah. Kamera full-frame dslr canon sudah banyak. Akan tetapi kamera full-frame EOS-R merupakan kamera full-frame pertama canon. Eos R diperkenalkan sekitar quartal akhir 2018."),
    Camera(photo: UIImage(named: "lumix-s1-close-up")!, name: "Lumix S1", description: "Panasonic Lumix S1 dan S1R sudah resmi masuk di indonesia. Panasonic Indonesia pun sudah mengumumkan harga Lumix S1. Saat ini S1 di Indonesia dijual dengan 2 paket yaitu paket body only dan paket body dengan lensa 24-105. Di indonesia S1 body only bisa di beli dengan harga 38 juta. Dan untuk paket dengan lensa 24-105 bisa di beli dengan harga 52 juta rupiah. Dari kedua paket bundling tersebut hargany sudah termasuk dengan garansi 1 tahun dari Panasonic Gobel Indonesia."),
    Camera(photo: UIImage(named: "nikon-z-7")!, name: "Nikon Z7", description: "Nikon Z 7 adalah kamera mirrorless full-end full-end perusahaan. Ini fitur sensor BSI-CMOS 45,7MP, sistem AF hibrida dengan 493 poin dan cakupan 90% dan stabilisasi gambar dalam-tubuh 5-sumbu. Bodi yang kokoh mirip dengan desain pada D850 DSLR dan sepenuhnya tertutup terhadap debu dan kelembaban. Ini fitur jendela bidik elektronik 3,68M-dot dan memiringkan 3,2 inchi, 2,1M-dot LCD layar sentuh. Sebuah panel OLED pada pelat atas menampilkan pengaturan pemotretan saat ini. Foto disimpan pada kartu XQD."),
    Camera(photo: UIImage(named: "fujifilm-xt-4")!, name: "Fujifilm XT4", description: "Fujifilm mengatakan X-T4 dimaksudkan sebagai model saudara untuk X-T3 daripada pengganti langsung, tetapi ada perbedaan yang cukup antara keduanya yang mungkin ingin ditingkatkan oleh beberapa pengguna. Dan mungkin ada orang yang melihat seri X lagi, ingin tahu mana yang merupakan pilihan yang lebih baik."),
    Camera(photo: UIImage(named: "leica-m-10-monochrome")!, name: "Leica M10 Monochrome", description: "Leica M10 Monochrom adalah pengintai mono-saja ketiga perusahaan. Ini menggunakan sensor 40MP yang sama sekali baru, daripada meminjam chip 24MP dari model M10 lainnya. Kami pikir array filter Bayer adalah kreasi yang luar biasa, menghasilkan hasil yang secara besar-besaran melebihi kelemahannya, tetapi ada beberapa alasan mengapa tidak menggunakan filter warna lebih dari sekadar tipuan."),
    Camera(photo: UIImage(named: "sony-a7-iii")!, name: "Sony A7 Mark III", description: "Dibandingkan dengan pendahulunya, Sony a7 III telah diperbarui dalam hampir setiap cara; bila dibandingkan dengan opsi full frame lainnya yang harganya sama, a7 III terlihat seperti potongan di atas dalam banyak hal. Untuk fotografer generalis, penembak pernikahan dan acara, dan bahkan spesialis olahraga, a7 III mendapatkan banyak sekali hal yang tepat. Tetapi seperti dengan kamera full-frame Sony mirrorless sebelumnya, ada beberapa kelemahan yang bertahan dengan model baru ini."),
    Camera(photo: UIImage(named: "lumix-gh-5")!, name: "Lumix GH5", description: "Panasonic Lumix DC-GH5 adalah yang kelima dalam jajaran industri video yang berubah dan masih 'hybrid'. Dengan sensor Four Thirds 20MP dan set fitur video-sentris yang mendalam, sepertinya GH4 mengambil tempat di mana GH4 ditinggalkan sebagai favorit pembuat film indie dan fotografer yang minatnya menjelajah ke ranah karya film bergerak. Perangkat fitur GH5 bergerak jauh dari pendahulunya sehingga perusahaan mengatakan GH4 akan tetap dalam jajarannya sebagai opsi berbiaya lebih rendah bagi pengguna yang tidak membutuhkan kemampuan tambahan yang dibawa GH5."),
    Camera(photo: UIImage(named: "fujifilm-gfx-50s")!, name: "Fujifilm GFX 50S", description: "Fujifilm GFX 50S adalah kamera digital format medium pertama perusahaan. Ia menawarkan sensor CMOS 51,4MP 43,8 x 32,9mm dan menggunakan lensa G-mount baru, dengan faktor krop 0,79x. Ia menggunakan Pro Prosesor X yang sama dengan X-Pro2 dan X-T2 dan memiliki sistem autofokus deteksi titik 117. Bodinya ringkas dan ringan untuk kamera format medium dan memiliki LCD layar sentuh 3,2 inch yang dapat diartikulasikan dalam tiga arah. Sebuah jendela bidik elektronik OLED 3,69M-dot resolusi ultra-tinggi dapat dilepas dan adaptor opsional memungkinkannya memiringkan dan memutar Di bagian atas kamera terdapat LCD yang lebih kecil yang menampilkan informasi pemotretan. GFX memiliki mode Simulasi Film Fujifilm biasa, plus opsi Efek Chrome Warna yang baru. Ini juga mampu menangkap video Full HD hingga 30p. Genggaman baterai adalah opsional."),
    Camera(photo: UIImage(named:"nikon-d-780")!, name: "Nikon D780", description: "Nikon D780 adalah DSLR full-frame tingkat antusias yang mewarisi fitur dari model D5 dan D810 profesional perusahaan. Ini fitur sensor BSI-CMOS 24MP dipasangkan dengan prosesor Expeed 6, dengan ISO atas (diperluas) dari 204.800. Ia dapat memotret burst pada 7 fps dengan autofokus menerus. Saat memotret melalui jendela bidik ada sistem AF 51 titik, mirip dengan yang ada pada pendahulunya (D750), tetapi dengan algoritma yang ditingkatkan dipinjam dari D5. Dalam tampilan langsung, kamera menggunakan sistem hybrid (deteksi fase + kontras) untuk kinerja pemfokusan yang lebih cepat secara dramatis daripada model sebelumnya. D780 dapat menangkap video UHD 4K pada 30p dan video Full HD kecepatan tinggi pada 120p."),
    Camera(photo: UIImage(named: "leica-sl-2")!, name: "Leica SL2", description: "Leica SL2 adalah kamera full-frame 47 Megapixel yang menggunakan L-mount yang dikembangkan bersama oleh perusahaan dengan Panasonic dan Sigma. Ini memiliki stabilisasi gambar sensor-shift bawaan, dan kamera dapat memindahkan sensor untuk menghasilkan 187 gambar Megapixel. Bodi SL2 telah sepenuhnya didesain ulang sejak pendahulunya, membuatnya lebih mudah untuk dipegang dan dioperasikan, dengan sebagian besar kontrol pada layar sentuh. Ini telah mendapatkan peringkat IP54 untuk cuaca-sealing, juga. Prosesor 'Maestro III' yang baru memungkinkan AF lebih cepat dari pendahulunya serta pemotretan burst 20 fps dengan rana elektronik atau 10 fps dengan rana mekanis. LCD layar sentuh kamera sekarang berukuran 3,2 inch dan olahraga 2,1 juta titik, sedangkan resolusi EVF telah ditingkatkan menjadi 5,76 juta titik. SL2 memiliki dua slot kartu SD, yang keduanya kompatibel dengan media UHS-II berkecepatan tinggi.")
]
